# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.50.50"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder "../../builds", "/vagrant_data/builds"
  config.vm.synced_folder "../../scripts/debian", "/vagrant_data/install"

  config.vm.provider "virtualbox" do |vb|
        vb.name = "trusty64_build_box"
        vb.gui = false
        vb.memory = "512"
   end

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "puppet/manifests"
     puppet.manifest_file = "init.pp"
     puppet.module_path = "puppet/modules"
     puppet.options = "--verbose --debug"
  end

end
